import { Question } from './types';

// Palette for the Sober/Penitential Aesthetic
export const THEME = {
  colors: {
    gold: '#8B459E', // Primary Purple
    goldDim: '#5E3A6C', // Secondary
    darkBase: '#1A0A26', // Obsidian
    glass: 'rgba(37, 18, 53, 0.85)', // Obsidian Light Glass
    glassBorder: 'rgba(139, 69, 158, 0.2)', // Purple border
    textPrimary: '#E0D8E8', // Parchment
    textSecondary: '#C7B4C8', // Dim
    danger: '#9E2B2B', 
    success: '#064e3b', 
  }
};

export const CHILD_QUESTIONS: Question[] = [
  { id: 1, text: "Rezo as minhas orações?" },
  { id: 2, text: "Fui à Missa aos domingos?" },
  { id: 3, text: "Falei o nome de Deus em vão?" },
  { id: 4, text: "Fiz bagunça durante a Missa ou na igreja?" },
  { id: 5, text: "Ajudei lá em casa?" },
  { id: 6, text: "Fui egoísta? Tratei com carinho os meus pais e irmãos? Fui mal educado com eles?" },
  { id: 7, text: "Obedeci a meus pais e a meus professores?" },
  { id: 8, text: "Divido meus brinquedos com as outras crianças?" },
  { id: 9, text: "Fui impaciente? Fiquei irritado ou fui invejoso?" },
  { id: 10, text: "Insisti com teimosia em fazer a minha vontade?" },
  { id: 11, text: "Estou distraído e perco o tempo durante as aulas?" },
  { id: 12, text: "Faço o meu dever de casa da melhor maneira que posso? Colei nas provas?" },
  { id: 13, text: "Briguei? Bati em alguém?" },
  { id: 14, text: "Magoei alguém, falando mal dessa pessoa para outros?" },
  { id: 15, text: "Menti?" },
  { id: 16, text: "Roubei alguma coisa? Quebrei ou estraguei as coisas dos outros?" },
  { id: 17, text: "Dou bom exemplo?" },
  { id: 18, text: "Tenho incentivado os outros a fazer coisas erradas?" },
  { id: 19, text: "Fui egoísta nos meus pensamentos e ações?" },
  { id: 20, text: "Tenho ciúmes de alguém?" },
  { id: 21, text: "Deixei alguém fora dos meus jogos?" },
  { id: 22, text: "Rezei pelas pessoas e tentei ajudá-las a ficar mais perto de Deus?" }
];

export const YOUTH_QUESTIONS: Question[] = [
  { id: 1, text: "Neguei ou abandonei a minha fé? Tenho a preocupação de conhecê-la melhor? Recusei-me a defender a minha fé ou fiquei envergonhado dela?" },
  { id: 2, text: "Preferi a minha comodidade, fugindo do serviço aos demais? Tive a preocupação de aproximar os outros de Deus, com o meu exemplo e a minha palavra?" },
  { id: 3, text: "Disse o nome de Deus em vão? Pratiquei o espiritismo ou coloquei a minha confiança em adivinhos ou horóscopos? Manifestei falta de respeito pelas pessoas, lugares ou coisas santas?" },
  { id: 4, text: "Faltei voluntariamente à Missa nos domingos ou dias de preceito? Esqueci-me de Deus, descuidando as minhas orações?" },
  { id: 5, text: "Recebi a Sagrada Comunhão tendo algum pecado grave não confessado? Comunguei sem a devida reverência e sem o devido agradecimento?" },
  { id: 6, text: "Deixei de ser prestativo em casa? Deixei de dar carinho aos meus pais e irmãos?" },
  { id: 7, text: "Fui impaciente, fiquei irritado ou fui invejoso? Guardei ressentimentos ou fiquei relutante em perdoar? Estive de mau humor ou cedi à ironia? Julguei mal ou senti ódio por alguém?" },
  { id: 8, text: "Deixei de estudar com empenho na escola? Cedi à preguiça? Tratei os professores ou os adultos com desrespeito?" },
  { id: 9, text: "Fui violento ou participei de brigas? Fiz mal a alguma pessoa insultando-a ou falando mal dela? Revelei algum segredo ou disse coisas somente para fazer mal a outros?" },
  { id: 10, text: "Tive pensamentos impuros? Falei de maneira obscena? Cometi atos impuros sozinho ou com outras pessoas? Vi imagens, sites ou vídeos pornográficos?" },
  { id: 11, text: "Contei mentiras para me desculpar, para magoar os outros ou para enaltecer a minha imagem?" },
  { id: 12, text: "Roubei alguma coisa? Estraguei de propósito o que era dos outros? Fiz algum ato de vandalismo?" },
  { id: 13, text: "Tenho inveja dos outros, da sua aparência, da sua popularidade, do seu trabalho, do seu dinheiro? Deixo que o coração fique preso ao desejo de possuir?" },
  { id: 14, text: "Encorajei outros a se comportarem mal?" },
  { id: 15, text: "Consumi álcool em excesso? Usei drogas?" },
  { id: 16, text: "Fui vaidoso ou egoísta em meus pensamentos ou ações?" },
];

export const ADULT_QUESTIONS: Question[] = [
  { id: 1, text: "Neguei ou abandonei a minha fé? Tenho a preocupação de conhecê-la melhor? Recusei-me a defender a minha fé ou fiquei envergonhado dela? Existe algum aspecto da minha fé que eu ainda não aceito?" },
  { id: 2, text: "Disse o nome de Deus em vão? Pratiquei o espiritismo ou coloquei a minha confiança em adivinhos ou horóscopos? Manifestei falta de respeito pelas pessoas, lugares ou coisas santas?" },
  { id: 3, text: "Faltei voluntariamente à Missa nos domingos ou dias de preceito?" },
  { id: 4, text: "Recebi a Sagrada Comunhão tendo algum pecado grave não confessado? Recebi a Comunhão sem agradecimento ou sem a devida reverência?" },
  { id: 5, text: "Fui impaciente, fiquei irritado ou fui invejoso?" },
  { id: 6, text: "Guardei ressentimentos ou relutei em perdoar?" },
  { id: 7, text: "Fui violento nas palavras ou ações com outros?" },
  { id: 8, text: "Colaborei ou encorajei alguém a fazer um aborto ou a destruir embriões humanos, a praticar a eutanásia ou qualquer outro meio de acabar com a vida?" },
  { id: 9, text: "Tive ódio ou juízos críticos, em pensamentos ou ações? Olhei os outros com desprezo?" },
  { id: 10, text: "Falei mal dos outros, transformando o assunto em fofoca?" },
  { id: 11, text: "Abusei de bebidas alcoólicas? Usei drogas?" },
  { id: 12, text: "Fiquei vendo vídeos ou sites pornográficos? Cometi atos impuros, sozinho ou com outras pessoas? Estou morando com alguém como se fosse casado, sem que o seja?" },
  { id: 13, text: "Deixei de amar o meu cônjuge mais do que a qualquer outra pessoa? Coloco meu casamento em primeiro lugar? E os meus filhos? Tenho uma atitude aberta para novos filhos?" },
  { id: 14, text: "Trabalho de modo desordenado? Ocupando tempo e energias que deveria dedicar à minha família e aos amigos?" },
  { id: 15, text: "Fui orgulhoso ou egoísta em meus pensamentos e ações? Deixei de ajudar os pobres e os necessitados? Gastei dinheiro com o meu conforto e luxo pessoal, esquecendo as minhas responsabilidades para com os outros e para com a Igreja?" },
  { id: 16, text: "Disse mentiras? Fui honesto e diligente no meu trabalho? Roubei ou enganei alguém no trabalho?" },
  { id: 17, text: "Cedi à preguiça? Preferi a comodidade ao invés do serviço aos demais?" },
  { id: 18, text: "Descuidei a minha responsabilidade de aproximar de Deus os outros, com o meu exemplo e a minha palavra?" },
];

export const PRIEST_QUESTIONS: Question[] = [
    { id: 1, text: "Tenho sido negligente com a busca pela santidade no meu ministério? Duvido, na prática, que a fecundidade do meu trabalho venha de Deus e resisto a me identificar com Cristo e a dar a vida pela salvação do mundo?" },
    { id: 2, text: "O Santo Sacrifício da Missa tornou-se algo periférico em minha vida interior? Sou negligente na preparação, celebro de forma mecânica e ignoro o momento de recolhimento em ação de graças? A Missa deixou de ser o ponto de referência da minha jornada, de modo que falho em louvar a Deus, em ser grato por seus benefícios e em buscar reparação pelos meus pecados e pelos da humanidade?" },
    { id: 3, text: "Trato a Missa com arbitrariedade, ignorando os ritos e as normas? Sou indiferente à Presença Real no Sacrário e descuidado com os vasos e vestes sagradas, esquecendo que atuo in persona Christi?" },
    { id: 4, text: "Sinto tédio ou impaciência diante do Santíssimo, evitando a adoração silenciosa? Sou infiel à visita diária ao Sacrário ou o trato apenas como uma obrigação burocrática em minha rotina?" },
    { id: 5, text: "Tenho sido negligente com a minha meditação diária, permitindo que as distrações me afastem de Deus e me deixem sem a luz do Senhor, a quem pretendo servir? Sou omisso na meditação assídua da Sagrada Escritura? Recito as minhas orações habituais de forma distraída, meramente formal e apressada?" },
    { id: 6, text: "Tenho falhado na celebração quotidiana da Liturgia das Horas, omitindo partes ou rezando-a de forma indigna, dispersa e sem devoção? Sou infiel ao meu compromisso com Cristo nesta dimensão essencial do meu ministério, ignorando que devo orar em nome de toda a Igreja?" },
    { id: 7, text: "Deixei que Nosso Senhor Jesus Cristo perdesse o lugar de verdadeiro amor da minha vida? Encaro o celibato como um fardo e consenti em pensamentos ou atos impuros? Fui imprudente em ocasiões próximas de pecado, relaxado na guarda da vista ou nos limites com as pessoas, dando um contratestemunho da pureza?" },
    { id: 8, text: "Tenho permitido que a preguiça e a fraqueza de caráter dominem minha conduta? Minhas conversas tornaram-se mundanas e vazias de sentido sobrenatural? Sou incoerente em minhas ações, agindo de forma dissociada da minha condição de sacerdote?" },
    { id: 9, text: "Tenho desprezo pela pobreza ou me apeguei às coisas materiais? Sou resistente a renunciar às minhas comodidades e projetos pessoais pelo Reino? Acumulei o supérfluo e vivo o repouso como se estivesse de folga de Deus, esquecendo que sou sacerdote em tempo integral?" },
    { id: 10, text: "Existem em minha vida pecados de soberba: dificuldades interiores, suscetibilidade, irritação, resistência a perdoar, tendência ao desencorajamento, etc.? Peço a Deus a virtude da humildade?" },
    { id: 11, text: "Duvido, na prática, de que ao agir in persona Christi estou diretamente vinculado ao Corpo de Cristo, que é a Igreja? Tenho um sentimento de indiferença ou amargura em relação à Igreja, servindo ao seu crescimento e às suas causas por mera obrigação, sem amor e sem preocupação real com cada um de seus membros e com a humanidade?" },
    { id: 12, text: "Fui rebelde ou resistente ao receber as indicações, conselhos ou correções do meu Ordinário? Na prática, ignoro o princípio Nihil sine episcopo – nada sem o bispo – conduzindo o meu ministério sacerdotal de forma independente e isolada? Sou negligente na oração pelo Santo Padre, distanciando-me ou duvidando dos seus ensinamentos e intenções?" },
    { id: 13, text: "Tenho sido negligente, frio ou apático com meus irmãos sacerdotes? Semeei divisões com críticas ou fui indiferente aos que sofrem? Falhei na fraternidade, deixando algum irmão isolado, ou tratei clérigos e leigos com impaciência e dureza?" },
    { id: 14, text: "Fui omisso no estudo e no conhecimento profundo dos ensinamentos da Igreja? Falho em assimilar a doutrina e a transmito de forma distorcida ou infiel? Sou indiferente ao fato de que ensinar o que não corresponde ao Magistério, solene ou ordinário, é um grave abuso que coloca em risco a salvação das almas?" },
    { id: 15, text: "Falhei em levar os fiéis aos sacramentos pela pregação? Sou negligente com minha própria confissão? Sou mesquinho na dedicação ao confessionário e indisponível para a direção espiritual? Preparo minhas pregações de forma improvisada e prego com tibieza, sem zelo ou amor a Deus?" },
    { id: 16, text: "Sou indiferente aos sinais de vocação ao meu redor? Negligencio o dever de pregar a chamada universal à santidade, deixando os fiéis na mediocridade? Falho em pedir orações pelas vocações e pela santificação do clero, confiando apenas em esforços humanos?" },
    { id: 17, text: "Vivo para mim mesmo, esquecendo-me de servir aos outros? Oculto a caridade por omissão ou vaidade? Sinto repulsa diante da Cruz, falhando em ver nela o triunfo do amor? Dou ao meu dia a marca do comodismo e trato a autoridade como privilégio pessoal em vez de serviço às almas?" },
    { id: 18, text: "Fui mesquinho na oração e no sacrifício pelas almas que Deus me confiou, agindo com preguiça e egoísmo? Cumpro os meus deveres pastorais como uma obrigação enfadonha e burocrática, sem zelo real pela salvação das pessoas? Sou indiferente e negligente com as almas dos fiéis defuntos, esquecendo-me de oferecer sufrágios e orações por elas?" },
    { id: 19, text: "Sinto-me distante da Virgem Maria, Mãe dos sacerdotes, falhando em amá-la e em levar as almas a Jesus? Deixei murchar minha piedade mariana ou sou negligente com o Terço? Tento lutar contra o demônio e o mundanismo contando apenas com minhas próprias forças, ignorando a intercessão materna de Maria?" },
    { id: 20, text: "Sou negligente ou apressado ao administrar os sacramentos aos moribundos? Omito a doutrina dos Novíssimos em minha pregação por medo ou mundanismo? Sou presunçoso a ponto de não pedir a perseverança final e esqueço-me de sufragar as almas dos fiéis defuntos?" }
];

export const GENERAL_CONFESSION_QUESTIONS: Question[] = [
    { id: 1, text: "Faz muito tempo que não me confesso? Há quanto tempo estou longe do sacramento da confissão?" },
    { id: 2, text: "Escondi, conscientemente, algum pecado grave em minhas confissões passadas?" },
    { id: 3, text: "Confessei, o melhor que me lembrava, o número de vezes que cometi cada pecado grave?" },
    { id: 4, text: "Confessei com clareza os meus pecados ou fui muito genérico?" },
    { id: 5, text: "Cumpri a penitência que o sacerdote me deu?" },
    { id: 6, text: "Reparei as injustiças que cometi?" },
    { id: 7, text: "Comunguei alguma vez em pecado mortal?" },
    { id: 8, text: "Estou verdadeiramente arrependido dos meus pecados e luto para não voltar a cometê-los?" },
    { id: 9, text: "Tenho o hábito de cometer um determinado pecado mortal?" },
    { id: 10, text: "Já me confessei deste pecado e mesmo assim continuo com o vício?" },
    { id: 11, text: "Deixei de conhecer por culpa própria as verdades básicas da fé? Como a Santíssima Trindade, a Encarnação, Morte e Ressurreição de Cristo, o Juízo Final e os Sacramentos? Sei que Deus recompensa os bons no Céu e pune os maus no Inferno, e conheço as orações fundamentais como o Pai Nosso?" },
    { id: 12, text: "Neguei ou duvidei voluntariamente de algo que a Igreja ensina, mesmo após ter sido instruído? Recuso-me a acreditar em verdades de fé já explicadas, como a existência do Inferno, dos demônios ou de qualquer outro dogma católico?" },
    { id: 13, text: "Acreditei, segui ou professei algum ensinamento, consciente de que ele era incompatível com a fé católica?" },
    { id: 14, text: "Participei ativamente de cultos ou cerimônias de outras religiões, como se fossem equivalentes à Igreja Católica? Tenho consciência de que frequentar esses ambientes, mesmo como espectador, pode abalar minha fé ou causar escândalo a outros fiéis?" },
    { id: 15, text: "Sou membro ou fiz parte de alguma organização religiosa não católica? Como de algum grupo anticatólico ou de alguma sociedade secreta como a Maçonaria?" },
    { id: 16, text: "Consumi livros, músicas ou programas que atacam Deus, a Igreja ou a moral católica? Tenho consciência de que expor-me a conteúdos que zombam da fé ou promovem o pecado, sem uma necessidade real e precaução, coloca em risco a minha salvação?" },
    { id: 17, text: "Pratiquei ou colaborei com superstições e idolatrias, como consulta a búzios, cartas, tarô, horóscopo ou previsão do futuro? Participei de rituais de espiritismo, candomblé, umbanda, magia, reiki ou crenças da Nova Era, buscando orientação ou cura fora de Deus?" },
    { id: 18, text: "Participei de reuniões espíritas? Invoquei espíritos? Recebi passe? Acreditei em reencarnação?" },
    { id: 19, text: "Invoquei a Satanás? Li textos, assisti a vídeos e filmes ou ouvi músicas que invocam explicitamente a Satanás?" },
    { id: 20, text: "Não professei externamente a minha fé católica quando havia necessidade grave de fazê-lo?" },
    { id: 21, text: "Recebi os sacramentos sem respeito ou sem fé? Recebi o Crisma, a Eucaristia, o Matrimônio, a Ordem em pecado mortal?" },
    { id: 22, text: "Desesperei da salvação, achando que os meus pecados eram maiores que a misericórdia de Deus?" },
    { id: 23, text: "Pequei por presunção, esperando que alcançaria a salvação sem ter que fugir do pecado e guardar os Mandamentos?" },
    { id: 24, text: "Acreditei na falsa doutrina que ensina que Deus, por ser misericordioso, irá salvar todas as pessoas ainda que elas não deixem o pecado?" },
    { id: 25, text: "Tive ódio a Deus? Revoltei-me contra Deus, por exemplo, por ter nascido com esta aparência, com este sexo (masculino ou feminino), com esta condição social ou por ter perdido um parente?" },
    { id: 26, text: "Cometi blasfêmia dizendo injúrias contra Deus, os santos ou coisas sagradas? Usei palavras ou gestos de desprezo, como quebrar imagens e amaldiçoar o que é santo, ou atribuí a criaturas poderes que pertencem apenas a Deus? Escandalizei outras pessoas com esse comportamento?" },
    { id: 27, text: "Irritei alguém com o propósito de fazê-lo praguejar ou blasfemar contra Deus?" },
    { id: 28, text: "Fiz juramentos falsos ou prometi praticar atos desonestos usando o nome de Deus, dos santos ou de coisas sagradas? Jurei cometer algum pecado ou prejudicar alguém invocando o testemunho divino?" },
    { id: 29, text: "Fiz uma promessa a Deus e não a cumpri? Tenho consciência de que, se não puder cumpri-la, devo pedir a um Bispo ou Pároco que a troque por outra obra ou me dispense, pois o descumprimento deliberado é um pecado?" },
    { id: 30, text: "Zombei (por palavras, piadas ou atos) de Deus, de Nossa Senhora, dos santos e de suas imagens, da Igreja, dos sacramentos ou de quaisquer coisas santas? Incentivei que outros zombassem, rissem e desprezassem?" },
    { id: 31, text: "Faltei à Missa aos domingos ou nos dias de guarda (como 1º de janeiro, Corpus Christi, 8 e 25 de dezembro) por culpa própria? Tenho consciência de que o preceito exige presença física na igreja e atenção mínima, não sendo cumprido ao assistir pela televisão ou rádio?" },
    { id: 32, text: "Nos domingos ou nos dias santos de guarda, cheguei atrasado à Missa ou saí mais cedo, por culpa própria?" },
    { id: 33, text: "Fiz, propositalmente, com que outras pessoas faltassem à Missa nos domingos ou dias santos de guarda, ou saíssem mais cedo, ou chegassem atrasadas?" },
    { id: 34, text: "Fiquei mais de um mês sem fazer ao menos uma oração sincera a Deus?" },
    { id: 35, text: "Nos domingos ou nos dias santos de guarda, realizei trabalhos, atividades ou negócios que me impediram de participar da Santa Missa? Obriguei que outras pessoas realizassem essas atividades, impedindo-lhes a participação na Santa Missa?" },
    { id: 36, text: "Trabalhei ou obriguei outros a trabalharem aos domingos e dias de guarda sem necessidade urgente? Tenho me esforçado para organizar minha rotina e meus negócios de modo que o descanso sagrado e o preceito da Missa sejam respeitados por mim e pelos meus subordinados?" },
    { id: 37, text: "Zombei, xinguei, maltratei ou ameacei os meus pais? Alegrei-me com o mal dos meus pais? Entristeci-me com o bem deles?" },
    { id: 38, text: "Desejei a desgraça aos meus pais? Desejei a morte aos meus pais? Desejei, por egoísmo, receber a herança?" },
    { id: 39, text: "Negligencio a oração pelos meus pais? Rezo para que eles não morram em pecado mortal ou, caso já tenham falecido, busco sufragar suas almas com orações e missas, especialmente no dia de Finados?" },
    { id: 40, text: "Não ajudei os meus pais em situações de grave necessidade material (alimentação, vestes, habitação, remédios), sendo que era possível para mim ajudá-los? Abandonei-os em suas doenças físicas ou emocionais? Abandonei-os na velhice?" },
    { id: 41, text: "Negligenciei o socorro espiritual aos meus pais quando mais precisavam? Deixei de chamar um sacerdote para administrar os sacramentos em caso de doença grave ou não providenciei o funeral cristão para eles, mesmo tendo condições de fazê-lo?" },
    { id: 42, text: "Agressi fisicamente meus pais ou levantei a mão contra eles? Tenho consciência de que qualquer agressão física aos pais é um pecado grave, mesmo que não tenha causado ferimentos leves?" },
    { id: 43, text: "Entristeci gravemente os meus pais com palavras, gestos ou ações?" },
    { id: 44, text: "Desobedeci aos meus pais em assuntos importantes, como ir à Missa, evitar más companhias ou festas indecentes? Tenho consciência de que devo obediência a eles enquanto viver sob o seu teto, com excessão caso me ordenem algo contrário à Lei de Deus ou à moral cristã?" },
    { id: 45, text: "Roubei alguma coisa dos meus pais?" },
    { id: 46, text: "Se sou casado: Zombei, xinguei, maltratei ou ameacei o meu cônjuge? Impedi que o meu cônjuge cumprisse seus deveres religiosos?" },
    { id: 47, text: "Deixei de batizar meus filhos o mais rápido possível por negligência?" },
    { id: 48, text: "Falhei na obrigação de educar meus filhos na fé católica, deixando de ensinar a doutrina e a importância dos sacramentos? Tenho incentivado meus filhos, a partir dos sete anos, a se confessarem regularmente para que vivam em estado de graça?" },
    { id: 49, text: "Deixei de sustentar os meus filhos? " },
    { id: 50, text: "Impedi meus filhos de irem à Missa aos domingos, de rezarem ou de cumprirem seus deveres religiosos?" },
    { id: 51, text: "Permiti que o namorado da minha filha (ou vice-versa) dormisse junto com ela?" },
    { id: 52, text: "Permiti que meus filhos lessem livros, ouvissem músicas ou assistissem a programas imorais, sexuais ou obscenos? Permiti que meus filhos frequentassem lugares suspeitos ou fossem a festas indecentes? Permiti que meus filhos tivessem companhias perigosas?" },
    { id: 53, text: "Deixei de corrigir os vícios e pecados graves dos meus filhos?" },
    { id: 54, text: "Castiguei os meus filhos com ódio no coração?" },
    { id: 55, text: "Fui mau exemplo para os meus filhos, dando-lhes ocasião de imitarem meus pecados graves ou de se escandalizarem com eles? " },
    { id: 56, text: "Desejei o mal a alguém? Desejei a doença ou a desgraça a alguém? Desejei o Inferno a alguém?" },
    { id: 57, text: "Agredi injustamente alguma pessoa?" },
    { id: 58, text: "Ofendi alguém, xingando, amaldiçoando, zombando? Escandalizei outras pessoas com tais ofensas?" },
    { id: 59, text: "Alimentei desejos de vingança ou ódio contra alguém? Tenho consciência de que, embora seja lícito desejar que a justiça humana seja feita contra um criminoso, é pecado desejar o mal por puro rancor ou vingança pessoal?" },
    { id: 60, text: "Matei uma pessoa? Quis matar ou procurei matar alguém?" },
    { id: 61, text: "Fiz ou tentei fazer aborto? Aconselhei ou ajudei alguém a fazer aborto? Defendi que as pessoas têm o direito de fazer aborto?" },
    { id: 62, text: "Apoiei, conscientemente, políticos que promovem o aborto, a eutanásia, o divórcio, a ideologia de gênero, o homossexualismo, a legalização das drogas, a abolição da propriedade privada?" },
    { id: 63, text: "Usei métodos abortivos ou que impedem a implantação da vida, como anticoncepcionais, DIU ou a pílula do dia seguinte? Tenho consciência de que o uso desses meios atenta contra a vida humana em seu início e é um pecado grave contra a vontade de Deus?" },
    { id: 64, text: "Pratiquei a eutanásia, apressando a morte de uma pessoa idosa ou doente? Aconselhei alguém a praticar a eutanásia? Defendi que as pessoas têm direito à eutanásia?" },
    { id: 65, text: "Fiz fertilização in vitro? Obriguei ou aconselhei o uso desse método? Afirmei ou defendi que uma pessoa pode usar métodos artificiais de concepção?" },
    { id: 66, text: "Retirei partes do meu corpo desnecessariamente ou realizei esterilização, como vasectomia ou ligadura de trompas? Tenho consciência de que cirurgias de mutilação ou que retiram a fertilidade só são permitidas para salvar a vida ou tratar doenças graves, e nunca por conveniência pessoal?" },
    { id: 67, text: "Tentei diretamente o suicídio? Induzi, instiguei ou auxiliei alguém a praticar suicídio?" },
    { id: 68, text: "Usei, por mero prazer, bebidas alcoólicas até perder completamente o uso da razão? Usei drogas ilícitas?" },
    { id: 69, text: "Cooperei diretamente com o pecado de outros, fornecendo ou facilitando meios para atos ilícitos? Isso inclui indicar ou vender anticoncepcionais e esterilizações, distribuir pornografia ou drogas, e ceder espaços ou talentos para eventos e festas claramente pecaminosos." },
    { id: 70, text: "Deixei de corrigir alguém que estava em pecado grave ou prestes a cometê-lo? Mesmo sabendo que a pessoa poderia mudar e que eu poderia ajudá-la sem sofrer um grave prejuízo pessoal? Tenho consciência de que omitir a correção fraterna, quando há esperança de conversão, é uma falta contra a caridade?" },
    { id: 71, text: "Tendo sido batizado na Igreja Católica, vivi uma 'união estável' ou um casamento meramente civil com alguém?" },
    { id: 72, text: "Sendo casado na Igreja, neguei a relação sexual ao meu cônjuge sem uma causa grave? Tenho consciência de que os esposos têm direito ao corpo um do outro, a menos que haja motivos como adultério não arrependido, embriaguez, doença contagiosa ou quando o parceiro exige práticas que pervertem o ato (uso de preservativos, anticoncepcionais ou atos impuros)." },
    { id: 73, text: "Usei métodos contraceptivos (por exemplo: pílula do dia seguinte, anticoncepcional, DIU, camisinha)? Obriguei ou aconselhei o uso de contraceptivos? Afirmei ou defendi que uma pessoa pode usar métodos contraceptivos?" },
    { id: 74, text: "Usei métodos artificiais de concepção que dispensam a relação sexual? Obriguei ou aconselhei o uso desses métodos? Afirmei ou defendi que uma pessoa pode usar métodos artificiais de concepção?" },
    { id: 75, text: "Pratiquei o onanismo ou o coito interrompido? Tenho consciência de que ejacular intencionalmente fora do órgão sexual da mulher para evitar a gravidez é um pecado grave que desvirtua o ato conjugal?" },
    { id: 76, text: "Vi pornografia com meu cônjuge? Obriguei meu cônjuge a ver pornografia?" },
    { id: 77, text: "Cometi adultério? Ao confessar este pecado, especifique ao sacerdote a condição da outra pessoa (se era casada, solteira, se houve abuso de vulnerável, ou se era alguém consagrado a Deus), pois essas circunstâncias podem agravar a falta." },
    { id: 78, text: "Sou casado na Igreja e causei a minha separação do meu cônjuge?" },
    { id: 79, text: "Sendo casado na Igreja e, após uma separação, cometi adultério através de namoros ou de uma segunda união (como morar junto ou casar apenas no civil)? Tenho consciência de que, aos olhos de Deus, o vínculo do matrimônio religioso é indissolúvel e que uma nova união sem a nulidade da anterior constitui pecado grave?" },
    { id: 80, text: "Pratiquei sexo sem ser casado (fornicação)? Especifique ao confessor a condição da outra pessoa (se era solteira, casada, consagrada a Deus, menor de idade ou do mesmo sexo), pois tais circunstâncias alteram a natureza ou a gravidade do pecado." },
    { id: 81, text: "Toquei uma criança buscando satisfação sexual? Tive relação sexual com uma criança?" },
    { id: 82, text: "Usei de violência, física ou moral, para forçar alguém a um pecado contra a castidade? Abusei da minha influência ou autoridade para seduzir ou coagir outra pessoa? Declare ao sacerdote as circunstâncias e a condição da pessoa envolvida (se era menor de idade, pessoa vulnerável, consagrada a Deus ou do mesmo sexo), devido à extrema gravidade desses atos." },
    { id: 83, text: "Cometi algum pecado sexual contra a natureza, por exemplo: homossexualismo, incesto (com parentes de sangue), bestialismo (com animais)?" },
    { id: 84, text: "Defendi ou apoiei o sexo livre, a poligamia, o divórcio, o adultério, o homossexualismo, a mudança de sexo, o incesto, o bestialismo, a pedofilia, a ideologia de gênero? Afirmei ou defendi que, se as pessoas 'se amam', elas têm o direito de fazer essas coisas?" },
    { id: 85, text: "Pequei por pornografia assistindo a vídeos, vendo fotos ou lendo conteúdos sexuais ou eróticos? Tenho o hábito de cair nesse pecado ou mantenho as ocasiões que me levam a ele? Confessei-me anteriormente sem o firme propósito de abandonar essas práticas ou de evitar o que me faz cair?" },
    { id: 86, text: "Divulguei textos, imagens ou vídeos pornográficos? Mantive o recebimento desses vídeos ou imagens, por exemplo, não saindo daquele grupo de rede social em que as pessoas enviam pornografia?" },
    { id: 87, text: "Pequei por masturbação ao tocar meu corpo buscando prazer sexual? Tenho o hábito de cair nesse pecado ou mantenho as situações que me levam a ele? Confessei-me antes sem o firme propósito de abandonar essa prática ou sem a decisão de evitar as ocasiões que me fazem cair?" },
    { id: 88, text: "Busquei prazer sexual por meio de toques, abraços ou beijos em outra pessoa? se estou namorando ou em noivado, atos que buscam a excitação (como beijos de língua ou toques íntimos) são pecados graves, pois preparam o corpo para uma relação que só é lícita no matrimônio? Se sou casado, tenho evitado carícias fora do ato conjugal que levem ao perigo de polução (ejaculação)?" },
    { id: 89, text: "Consenti em pensamentos, desejos ou olhares contra a castidade? Deleitei-me voluntariamente em imagens mentais impuras ou permaneci olhando para alguém com desejo sexual? Declare ao sacerdote quem foi o objeto desses pensamentos ou olhares (se pessoa casada, parente, criança, pessoa consagrada ou do mesmo sexo), pois essas circunstâncias alteram a natureza do pecado?" },
    { id: 90, text: "Sendo casado, pratiquei o ato sexual pensando voluntariamente em outra pessoa?" },
    { id: 91, text: "Promovi conversas eróticas com o fim de buscar prazer sexual? Ouvi conversas eróticas consentindo no prazer sexual que elas me causavam?" },
    { id: 92, text: "Induzi outras pessoas ao pecado ou ensinei o pecado a alguém?" },
    { id: 93, text: "Escandalizei alguém com conversas eróticas ou obscenas? Tenho consciência de que a gravidade desse pecado aumenta quando praticado diante de crianças ou por quem possui autoridade e responsabilidade sobre os outros, como pais ou sacerdotes?" },
    { id: 94, text: "Ouvi músicas eróticas e consenti no prazer sexual que me causaram? Escandalizei alguém com tais músicas?" },
    { id: 95, text: "Expus-me (sendo homem ou mulher) publicamente com roupas indecentes (coladas, decotadas, curtas ou transparentes)? Tive a intenção de seduzir ou sabendo que elas seriam escandalosas para os outros? Ao decidir abandonar essas vestes, devo descartá-las em vez de doá-las, para não induzir outras pessoas ao mesmo pecado." },
    { id: 96, text: "Roubei alguma coisa? O que foi e qual o valor aproximado? Quantas vezes pratiquei o roubo? Tenho o firme propósito de restituir o que foi levado ou de reparar o dano causado ao dono? Tenho consciência de que a confissão exige a intenção real de devolver o bem ou o seu valor, e que devo pedir orientação ao sacerdote sobre como realizar essa reparação de forma justa." },
    { id: 97, text: "Danifiquei injustamente a propriedade ou os bens de outra pessoa? Realizei a reparação financeira ou material do dano causado? Só é lícito causar dano a um bem alheio em casos de autoridade moral para evitar um mal maior (como um pai que destrói material pecaminoso de um filho)? Fora dessas exceções, entendo que sou obrigado a reparar o prejuízo que causei injustamente?" },
    { id: 98, text: "Obtive algum bem ou vantagem por meio de fraude ou enganação?" },
    { id: 99, text: "Perdi meus bens no jogo, causando prejuízo a mim ou aos meus dependentes?" },
    { id: 100, text: "Recusei-me a pagar alguma dívida? Recusei-me a devolver alguma coisa emprestada?" },
    { id: 101, text: "Adquiri alguma coisa que sabia ter sido roubada?" },
    { id: 102, text: "Lesei o meu patrão, não trabalhando honestamente como é dever de um funcionário?" },
    { id: 103, text: "Recusei-me a pagar o salário aos meus empregados? Atrasei o salário dos meus empregados sem uma justa causa?" },
    { id: 104, text: "Forcei os meus funcionários a trabalharem além da medida, impedindo-lhes, por exemplo, o devido descanso e a presença na Santa Missa aos domingos e dias santos de guarda?" },
    { id: 105, text: "Recusei-me a ajudar alguém que estava em extrema necessidade, embora fosse possível fazê-lo?" },
    { id: 106, text: "Fiquei triste ou com raiva por ver que uma pessoa tinha algum bem material que eu não possuía?" },
    { id: 107, text: "Senti tristeza ou raiva pelas virtudes, inteligência ou dons espirituais de outra pessoa? Reconheço que invejar a graça de Deus no próximo é um pecado contra a caridade?" },
    { id: 108, text: "Dei mais valor aos bens materiais do que à minha salvação eterna?" },
    { id: 109, text: "Contei mentiras que causaram dano grave à honra ou aos bens de alguém? Tenho o hábito de mentir? Reconheço que, embora toda mentira seja pecado, o dano grave ao próximo torna a falta mortal?" },
    { id: 110, text: "Caluniei alguém, dizendo que a pessoa cometeu algum crime ou pecado grave que eu sabia claramente que ela não tinha cometido? Colaborei com a divulgação de calúnias? Reparei a calúnia ou estou disposto a repará-la?" },
    { id: 111, text: "Fiz julgamentos temerários, condenando alguém interiormente sem evidências suficientes? Reconheço que julgar as intenções alheias sem provas é uma falta contra a justiça e a caridade?" },
    { id: 112, text: "Revelei defeitos ou pecados graves de alguém sem necessidade (maledicência)? Tenho o hábito de falar mal dos outros? Entendo que ferir a reputação alheia sem motivo justo é um pecado grave contra a justiça e a caridade?" },
    { id: 113, text: "Revelei algum segredo importante, sendo que a pessoa esperava que eu guardasse sigilo? Tenho o hábito de revelar os segredos das pessoas?" },
    { id: 114, text: "Provoquei intrigas para criar inimizades entre as pessoas?" },
    { id: 115, text: "Jurei falso ou assinei documentos falsos? Usei documentos falsos?" },
    { id: 116, text: "Deixei de comungar ao menos uma vez ao ano durante o Tempo Pascal? Reconheço que, embora a Igreja recomende a comunhão frequente, o preceito mínimo obriga ao menos uma vez na Páscoa?" },
    { id: 117, text: "Quebrei o jejum eucarístico ao comer ou beber algo menos de uma hora antes de comungar? Tenho consciência de que apenas água e remédios são permitidos nesse período?" },
    { id: 118, text: "Deixei de cumprir o jejum na Quarta-feira de Cinzas ou na Sexta-feira Santa? Deixei de guardar a abstinência de carne em todas as sextas-feiras do ano ou na Quarta-feira de Cinzas, conforme manda a Igreja?" },
    { id: 119, text: "Confessei-me pelo menos uma vez ao ano?" },
    { id: 120, text: "Contribuí com o dízimo, ofertas ou doações para o sustento da Igreja, conforme minhas possibilidades? Reconheço o dever de auxiliar nas necessidades materiais da paróquia e no auxílio aos pobres?" },
];